In [1]:
import numpy as np

In [7]:
arr = np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [11]:
arr.T

array([[ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49],
       [10, 20, 30, 40, 50]])

In [13]:
np.dot(arr,arr.T)

array([[  385,   935,  1485,  2035,  2585],
       [  935,  2485,  4035,  5585,  7135],
       [ 1485,  4035,  6585,  9135, 11685],
       [ 2035,  5585,  9135, 12685, 16235],
       [ 2585,  7135, 11685, 16235, 20785]])

In [15]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781]])

In [21]:
A = np.random.randn(50).reshape(5,10)
A

array([[ 1.50191244, -0.96836978,  0.85434051,  0.88532968, -0.41414026,
        -0.78413368, -1.45721959,  1.21145069,  1.08519186,  0.9182128 ],
       [-1.39210019,  0.312746  , -2.26480656,  0.34756888, -0.70953917,
         1.58499598, -0.7558976 ,  0.63674491, -1.12223427,  0.17017561],
       [-1.4543679 ,  1.07272744, -2.12276298, -0.87750496,  0.04942596,
        -0.5532024 , -0.34753429,  0.48446028, -0.40006218,  0.01024748],
       [ 1.32823304,  0.43593078,  1.18968153, -0.41100117, -0.18508095,
         1.93154489, -0.49513821, -0.19834602, -0.57203756,  0.33111095],
       [-1.41440063, -1.71287469, -1.05060912, -0.85631221, -0.64651177,
        -0.30872288,  2.35055275,  0.75689136,  0.36746067, -0.41184979]])

In [25]:
max= np.maximum(arr,A)
max

array([[ 1.50191244,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  7.        ,  8.        ,  9.        , 10.        ],
       [11.        , 12.        , 13.        , 14.        , 15.        ,
        16.        , 17.        , 18.        , 19.        , 20.        ],
       [21.        , 22.        , 23.        , 24.        , 25.        ,
        26.        , 27.        , 28.        , 29.        , 30.        ],
       [31.        , 32.        , 33.        , 34.        , 35.        ,
        36.        , 37.        , 38.        , 39.        , 40.        ],
       [41.        , 42.        , 43.        , 44.        , 45.        ,
        46.        , 47.        , 48.        , 49.        , 50.        ]])

In [29]:
min = np.minimum(arr,A)
min

array([[ 1.        , -0.96836978,  0.85434051,  0.88532968, -0.41414026,
        -0.78413368, -1.45721959,  1.21145069,  1.08519186,  0.9182128 ],
       [-1.39210019,  0.312746  , -2.26480656,  0.34756888, -0.70953917,
         1.58499598, -0.7558976 ,  0.63674491, -1.12223427,  0.17017561],
       [-1.4543679 ,  1.07272744, -2.12276298, -0.87750496,  0.04942596,
        -0.5532024 , -0.34753429,  0.48446028, -0.40006218,  0.01024748],
       [ 1.32823304,  0.43593078,  1.18968153, -0.41100117, -0.18508095,
         1.93154489, -0.49513821, -0.19834602, -0.57203756,  0.33111095],
       [-1.41440063, -1.71287469, -1.05060912, -0.85631221, -0.64651177,
        -0.30872288,  2.35055275,  0.75689136,  0.36746067, -0.41184979]])

In [31]:
combin= np.add(max,min)
combin

array([[ 2.50191244,  1.03163022,  3.85434051,  4.88532968,  4.58585974,
         5.21586632,  5.54278041,  9.21145069, 10.08519186, 10.9182128 ],
       [ 9.60789981, 12.312746  , 10.73519344, 14.34756888, 14.29046083,
        17.58499598, 16.2441024 , 18.63674491, 17.87776573, 20.17017561],
       [19.5456321 , 23.07272744, 20.87723702, 23.12249504, 25.04942596,
        25.4467976 , 26.65246571, 28.48446028, 28.59993782, 30.01024748],
       [32.32823304, 32.43593078, 34.18968153, 33.58899883, 34.81491905,
        37.93154489, 36.50486179, 37.80165398, 38.42796244, 40.33111095],
       [39.58559937, 40.28712531, 41.94939088, 43.14368779, 44.35348823,
        45.69127712, 49.35055275, 48.75689136, 49.36746067, 49.58815021]])