In [1]:
import numpy as np

In [3]:
arr = np.arange(5)

In [9]:
arr1 = np.arange(-5,5)


In [11]:
arr2 = np.arange(-4,5)

In [13]:
np.save('my_arr',arr)

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.load('my_arr.npy')

array([0, 1, 2, 3, 4])

In [19]:
np.savez('myz.npz',x=arr,y=arr1,z=arr2)

In [21]:
zip = np.load('myz.npz')

In [25]:
zip['y']

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [27]:
zip['z']

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [29]:
zip['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])