In [1]:
import numpy as np 
import pandas as pd 
from pandas import Series,DataFrame

In [3]:
df=DataFrame

In [7]:
ar1 = np.arange(9).reshape(3,3)
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([ar1,ar1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [11]:
np.concatenate([ar1,ar1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
ser1=Series([0,1,2],index=['T','U','V'])
ser1

T    0
U    1
V    2
dtype: int64

In [15]:
ser2=Series([3,4],index=['X','Y'])
ser2

X    3
Y    4
dtype: int64

In [19]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [21]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [23]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [29]:
dframe1=df(np.random.randn(4,3),columns=['x','y','z'])

dframe1

x         y         z
0 -0.073626 -1.813355 -2.176338
1 -1.971339  0.260400 -0.924837
2  0.574462 -0.695994  1.881047
3 -0.085933  1.401627 -0.796154

In [31]:
dframe2=df(np.random.randn(3,3),columns=['y','q','x'])
dframe2

y         q         x
0 -0.343002 -0.614904  0.773153
1  0.944816  0.239781  0.591119
2  0.170967 -0.888781 -0.846966

In [33]:
pd.concat([dframe1,dframe2])

x         y         z         q
0 -0.073626 -1.813355 -2.176338       NaN
1 -1.971339  0.260400 -0.924837       NaN
2  0.574462 -0.695994  1.881047       NaN
3 -0.085933  1.401627 -0.796154       NaN
0  0.773153 -0.343002       NaN -0.614904
1  0.591119  0.944816       NaN  0.239781
2 -0.846966  0.170967       NaN -0.888781

In [35]:
pd.concat([dframe1,dframe2],ignore_index=True)

x         y         z         q
0 -0.073626 -1.813355 -2.176338       NaN
1 -1.971339  0.260400 -0.924837       NaN
2  0.574462 -0.695994  1.881047       NaN
3 -0.085933  1.401627 -0.796154       NaN
4  0.773153 -0.343002       NaN -0.614904
5  0.591119  0.944816       NaN  0.239781
6 -0.846966  0.170967       NaN -0.888781

In [37]:
url = 'http://pandas.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'