In [1]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5,6,7,8,9,11]

In [4]:
my_array = np.array(my_list)

In [7]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [9]:
my_list2 = [2,3,4,5,6,7,8,9,11,12]

In [11]:
my_lists = [my_list,my_list2]

In [13]:
my_array2 = np.array(my_lists)

In [14]:
my_array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 11, 12]])

In [15]:
my_array2.shape

(2, 10)

In [18]:
my_array2.dtype

dtype('int32')

In [20]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [26]:
5/2

2.5

In [28]:
my_array3 = np.array([[1,2,3,4],[11,22,33,44]])

In [31]:
my_array3

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [33]:
arr = my_array3

In [34]:
arr

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [36]:
arr+5

array([[ 6,  7,  8,  9],
       [16, 27, 38, 49]])

In [38]:
arr**2

array([[   1,    4,    9,   16],
       [ 121,  484, 1089, 1936]])

In [39]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
arr[1]

array([11, 22, 33, 44])

In [42]:
arr[1]=10

In [43]:
arr

array([[ 1,  2,  3,  4],
       [10, 10, 10, 10]])

In [45]:
part = arr[1]

In [46]:
part

array([10, 10, 10, 10])

In [48]:
part[0:2]=9

In [50]:
part

array([ 9,  9, 10, 10])

In [51]:
arr

array([[ 1,  2,  3,  4],
       [ 9,  9, 10, 10]])

In [53]:
arr

array([[ 1,  2,  3,  4],
       [ 9,  9, 10, 10]])

In [54]:
vr = arr.copy()

In [56]:
vr

array([[ 1,  2,  3,  4],
       [ 9,  9, 10, 10]])

In [81]:
vr[:1,1:]

array([[2, 3, 4]])

In [98]:
arrays= np.zeros((10,10))

In [100]:
arrays

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
for i in range(10):
  arrays[i]=i

In [110]:
arrays

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])