In [1]:
import numpy as np
import pandas as pd 
from pandas import Series,DataFrame

In [3]:
dframe = DataFrame(np.arange(16).reshape(4,4))

In [7]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [9]:
blender =np.random.permutation(4)

In [11]:
blender

array([2, 0, 1, 3])

In [13]:
dframe.take(blender)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [15]:
box=np.array([1,2,3])

In [17]:
box

array([1, 2, 3])

In [19]:
shaker = np.random.randint(0,len(box),size=10)

In [21]:
shaker

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [23]:
hand = box.take(shaker)
hand

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 2])